-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity FFT053 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    data_IN_M_real_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_IN_M_real_ce0 : OUT STD_LOGIC;
    data_IN_M_real_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_IN_M_real_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_IN_M_real_ce1 : OUT STD_LOGIC;
    data_IN_M_real_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_IN_M_imag_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_IN_M_imag_ce0 : OUT STD_LOGIC;
    data_IN_M_imag_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_IN_M_imag_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_IN_M_imag_ce1 : OUT STD_LOGIC;
    data_IN_M_imag_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    data_OUT1_M_imag_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_OUT1_M_imag_ce0 : OUT STD_LOGIC;
    data_OUT1_M_imag_we0 : OUT STD_LOGIC;
    data_OUT1_M_imag_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_OUT1_M_imag_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_OUT1_M_imag_ce1 : OUT STD_LOGIC;
    data_OUT1_M_imag_we1 : OUT STD_LOGIC;
    data_OUT1_M_imag_d1 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_OUT1_M_real_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_OUT1_M_real_ce0 : OUT STD_LOGIC;
    data_OUT1_M_real_we0 : OUT STD_LOGIC;
    data_OUT1_M_real_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    data_OUT1_M_real_address1 : OUT STD_LOGIC_VECTOR (4 downto 0);
    data_OUT1_M_real_ce1 : OUT STD_LOGIC;
    data_OUT1_M_real_we1 : OUT STD_LOGIC;
    data_OUT1_M_real_d1 : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of FFT053 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state19 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal W_M_real65_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal W_M_real65_ce0 : STD_LOGIC;
    signal W_M_real65_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal W_M_imag61_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal W_M_imag61_ce0 : STD_LOGIC;
    signal W_M_imag61_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal butterfly_span_0_i_reg_176 : STD_LOGIC_VECTOR (31 downto 0);
    signal butterfly_pass_0_i_reg_187 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_0_i_reg_198 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln53_fu_249_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_state7_pp0_stage0_iter5 : BOOLEAN;
    signal ap_block_state8_pp0_stage0_iter6 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter7 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter8 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter9 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter10 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter11 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter12 : BOOLEAN;
    signal ap_block_state15_pp0_stage0_iter13 : BOOLEAN;
    signal ap_block_state16_pp0_stage0_iter14 : BOOLEAN;
    signal ap_block_state17_pp0_stage0_iter15 : BOOLEAN;
    signal ap_block_state18_pp0_stage0_iter16 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln53_reg_352_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter8_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter9_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter10_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter11_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter12_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter13_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter14_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln53_reg_352_pp0_iter15_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal i_fu_255_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal Ulimit_fu_273_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361 : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter1_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter2_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter3_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter4_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter5_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter6_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter7_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal Ulimit_reg_361_pp0_iter8_reg : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln58_5_fu_291_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter1_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter2_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter3_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter4_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter5_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter6_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter7_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter8_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter9_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln58_5_reg_376_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal select_ln61_fu_331_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal butterfly_pass_10_fu_339_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_r_M_real_reg_402 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_r_M_imag_reg_408 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_t_real_reg_414 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal p_t_imag_reg_420 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_233_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_i_i_i_reg_426 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_237_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_3_i_i_i_reg_431 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_241_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_5_i_i_i_reg_436 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_245_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_i_i_i_reg_441 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln59_fu_347_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln59_reg_446 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln59_reg_446_pp0_iter10_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln59_reg_446_pp0_iter11_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln59_reg_446_pp0_iter12_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln59_reg_446_pp0_iter13_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln59_reg_446_pp0_iter14_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln59_reg_446_pp0_iter15_reg : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_fu_209_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Product_M_real_reg_462 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_213_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Product_M_imag_reg_468 : STD_LOGIC_VECTOR (31 downto 0);
    signal p_r_M_real_5_reg_474 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal p_r_M_imag_5_reg_480 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_217_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal complex_M_real_writ_reg_486 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_221_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal complex_M_imag_writ_reg_491 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_225_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal complex_M_real_writ_5_reg_496 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_fu_229_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal complex_M_imag_writ_5_reg_501 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter14 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter15 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter16 : STD_LOGIC := '0';
    signal sext_ln58_fu_285_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal shl_ln56_fu_267_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal index_fu_261_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal Llimit_fu_279_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln63_fu_311_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal butterfly_pass_fu_317_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_297_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal butterfly_span_fu_305_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal butterfly_pass_9_fu_323_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state19 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state19 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component FFT_fsub_32ns_32nbkb IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT_fadd_32ns_32ncud IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT_fmul_32ns_32ndEe IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (31 downto 0);
        din1 : IN STD_LOGIC_VECTOR (31 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT053_W_M_real65 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component FFT053_W_M_imag61 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    W_M_real65_U : component FFT053_W_M_real65
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => W_M_real65_address0,
        ce0 => W_M_real65_ce0,
        q0 => W_M_real65_q0);

    W_M_imag61_U : component FFT053_W_M_imag61
    generic map (
        DataWidth => 32,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => W_M_imag61_address0,
        ce0 => W_M_imag61_ce0,
        q0 => W_M_imag61_q0);

    FFT_fsub_32ns_32nbkb_U10 : component FFT_fsub_32ns_32nbkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_i_i_i_reg_426,
        din1 => tmp_3_i_i_i_reg_431,
        ce => ap_const_logic_1,
        dout => grp_fu_209_p2);

    FFT_fadd_32ns_32ncud_U11 : component FFT_fadd_32ns_32ncud
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => tmp_5_i_i_i_reg_436,
        din1 => tmp_6_i_i_i_reg_441,
        ce => ap_const_logic_1,
        dout => grp_fu_213_p2);

    FFT_fsub_32ns_32nbkb_U12 : component FFT_fsub_32ns_32nbkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_real_5_reg_474,
        din1 => Product_M_real_reg_462,
        ce => ap_const_logic_1,
        dout => grp_fu_217_p2);

    FFT_fsub_32ns_32nbkb_U13 : component FFT_fsub_32ns_32nbkb
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_imag_5_reg_480,
        din1 => Product_M_imag_reg_468,
        ce => ap_const_logic_1,
        dout => grp_fu_221_p2);

    FFT_fadd_32ns_32ncud_U14 : component FFT_fadd_32ns_32ncud
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_real_5_reg_474,
        din1 => Product_M_real_reg_462,
        ce => ap_const_logic_1,
        dout => grp_fu_225_p2);

    FFT_fadd_32ns_32ncud_U15 : component FFT_fadd_32ns_32ncud
    generic map (
        ID => 1,
        NUM_STAGE => 5,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_imag_5_reg_480,
        din1 => Product_M_imag_reg_468,
        ce => ap_const_logic_1,
        dout => grp_fu_229_p2);

    FFT_fmul_32ns_32ndEe_U16 : component FFT_fmul_32ns_32ndEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_real_reg_402,
        din1 => p_t_real_reg_414,
        ce => ap_const_logic_1,
        dout => grp_fu_233_p2);

    FFT_fmul_32ns_32ndEe_U17 : component FFT_fmul_32ns_32ndEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_imag_reg_408,
        din1 => p_t_imag_reg_420,
        ce => ap_const_logic_1,
        dout => grp_fu_237_p2);

    FFT_fmul_32ns_32ndEe_U18 : component FFT_fmul_32ns_32ndEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_imag_reg_408,
        din1 => p_t_real_reg_414,
        ce => ap_const_logic_1,
        dout => grp_fu_241_p2);

    FFT_fmul_32ns_32ndEe_U19 : component FFT_fmul_32ns_32ndEe
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 32,
        din1_WIDTH => 32,
        dout_WIDTH => 32)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => p_r_M_real_reg_402,
        din1 => p_t_imag_reg_420,
        ce => ap_const_logic_1,
        dout => grp_fu_245_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter14_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter14 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter14 <= ap_enable_reg_pp0_iter13;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter15_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter15 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter15 <= ap_enable_reg_pp0_iter14;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter16_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter16 <= ap_enable_reg_pp0_iter15;
                elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter16 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    butterfly_pass_0_i_reg_187_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                butterfly_pass_0_i_reg_187 <= butterfly_pass_10_fu_339_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                butterfly_pass_0_i_reg_187 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    butterfly_span_0_i_reg_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                butterfly_span_0_i_reg_176 <= select_ln61_fu_331_p3;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                butterfly_span_0_i_reg_176 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    i_0_i_reg_198_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                i_0_i_reg_198 <= i_fu_255_p2;
            elsif ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_0_i_reg_198 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_352_pp0_iter9_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Product_M_imag_reg_468 <= grp_fu_213_p2;
                Product_M_real_reg_462 <= grp_fu_209_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_fu_249_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Ulimit_reg_361 <= Ulimit_fu_273_p2;
                sext_ln58_5_reg_376 <= sext_ln58_5_fu_291_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                Ulimit_reg_361_pp0_iter1_reg <= Ulimit_reg_361;
                icmp_ln53_reg_352 <= icmp_ln53_fu_249_p2;
                icmp_ln53_reg_352_pp0_iter1_reg <= icmp_ln53_reg_352;
                sext_ln58_5_reg_376_pp0_iter1_reg <= sext_ln58_5_reg_376;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                Ulimit_reg_361_pp0_iter2_reg <= Ulimit_reg_361_pp0_iter1_reg;
                Ulimit_reg_361_pp0_iter3_reg <= Ulimit_reg_361_pp0_iter2_reg;
                Ulimit_reg_361_pp0_iter4_reg <= Ulimit_reg_361_pp0_iter3_reg;
                Ulimit_reg_361_pp0_iter5_reg <= Ulimit_reg_361_pp0_iter4_reg;
                Ulimit_reg_361_pp0_iter6_reg <= Ulimit_reg_361_pp0_iter5_reg;
                Ulimit_reg_361_pp0_iter7_reg <= Ulimit_reg_361_pp0_iter6_reg;
                Ulimit_reg_361_pp0_iter8_reg <= Ulimit_reg_361_pp0_iter7_reg;
                icmp_ln53_reg_352_pp0_iter10_reg <= icmp_ln53_reg_352_pp0_iter9_reg;
                icmp_ln53_reg_352_pp0_iter11_reg <= icmp_ln53_reg_352_pp0_iter10_reg;
                icmp_ln53_reg_352_pp0_iter12_reg <= icmp_ln53_reg_352_pp0_iter11_reg;
                icmp_ln53_reg_352_pp0_iter13_reg <= icmp_ln53_reg_352_pp0_iter12_reg;
                icmp_ln53_reg_352_pp0_iter14_reg <= icmp_ln53_reg_352_pp0_iter13_reg;
                icmp_ln53_reg_352_pp0_iter15_reg <= icmp_ln53_reg_352_pp0_iter14_reg;
                icmp_ln53_reg_352_pp0_iter2_reg <= icmp_ln53_reg_352_pp0_iter1_reg;
                icmp_ln53_reg_352_pp0_iter3_reg <= icmp_ln53_reg_352_pp0_iter2_reg;
                icmp_ln53_reg_352_pp0_iter4_reg <= icmp_ln53_reg_352_pp0_iter3_reg;
                icmp_ln53_reg_352_pp0_iter5_reg <= icmp_ln53_reg_352_pp0_iter4_reg;
                icmp_ln53_reg_352_pp0_iter6_reg <= icmp_ln53_reg_352_pp0_iter5_reg;
                icmp_ln53_reg_352_pp0_iter7_reg <= icmp_ln53_reg_352_pp0_iter6_reg;
                icmp_ln53_reg_352_pp0_iter8_reg <= icmp_ln53_reg_352_pp0_iter7_reg;
                icmp_ln53_reg_352_pp0_iter9_reg <= icmp_ln53_reg_352_pp0_iter8_reg;
                sext_ln58_5_reg_376_pp0_iter10_reg <= sext_ln58_5_reg_376_pp0_iter9_reg;
                sext_ln58_5_reg_376_pp0_iter11_reg <= sext_ln58_5_reg_376_pp0_iter10_reg;
                sext_ln58_5_reg_376_pp0_iter12_reg <= sext_ln58_5_reg_376_pp0_iter11_reg;
                sext_ln58_5_reg_376_pp0_iter13_reg <= sext_ln58_5_reg_376_pp0_iter12_reg;
                sext_ln58_5_reg_376_pp0_iter14_reg <= sext_ln58_5_reg_376_pp0_iter13_reg;
                sext_ln58_5_reg_376_pp0_iter15_reg <= sext_ln58_5_reg_376_pp0_iter14_reg;
                sext_ln58_5_reg_376_pp0_iter2_reg <= sext_ln58_5_reg_376_pp0_iter1_reg;
                sext_ln58_5_reg_376_pp0_iter3_reg <= sext_ln58_5_reg_376_pp0_iter2_reg;
                sext_ln58_5_reg_376_pp0_iter4_reg <= sext_ln58_5_reg_376_pp0_iter3_reg;
                sext_ln58_5_reg_376_pp0_iter5_reg <= sext_ln58_5_reg_376_pp0_iter4_reg;
                sext_ln58_5_reg_376_pp0_iter6_reg <= sext_ln58_5_reg_376_pp0_iter5_reg;
                sext_ln58_5_reg_376_pp0_iter7_reg <= sext_ln58_5_reg_376_pp0_iter6_reg;
                sext_ln58_5_reg_376_pp0_iter8_reg <= sext_ln58_5_reg_376_pp0_iter7_reg;
                sext_ln58_5_reg_376_pp0_iter9_reg <= sext_ln58_5_reg_376_pp0_iter8_reg;
                sext_ln59_reg_446_pp0_iter10_reg <= sext_ln59_reg_446;
                sext_ln59_reg_446_pp0_iter11_reg <= sext_ln59_reg_446_pp0_iter10_reg;
                sext_ln59_reg_446_pp0_iter12_reg <= sext_ln59_reg_446_pp0_iter11_reg;
                sext_ln59_reg_446_pp0_iter13_reg <= sext_ln59_reg_446_pp0_iter12_reg;
                sext_ln59_reg_446_pp0_iter14_reg <= sext_ln59_reg_446_pp0_iter13_reg;
                sext_ln59_reg_446_pp0_iter15_reg <= sext_ln59_reg_446_pp0_iter14_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_352_pp0_iter14_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                complex_M_imag_writ_5_reg_501 <= grp_fu_229_p2;
                complex_M_imag_writ_reg_491 <= grp_fu_221_p2;
                complex_M_real_writ_5_reg_496 <= grp_fu_225_p2;
                complex_M_real_writ_reg_486 <= grp_fu_217_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter10 = ap_const_logic_1) and (icmp_ln53_reg_352_pp0_iter9_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_r_M_imag_5_reg_480 <= data_IN_M_imag_q1;
                p_r_M_real_5_reg_474 <= data_IN_M_real_q1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_352 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_r_M_imag_reg_408 <= W_M_imag61_q0;
                p_r_M_real_reg_402 <= W_M_real65_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_352 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                p_t_imag_reg_420 <= data_IN_M_imag_q0;
                p_t_real_reg_414 <= data_IN_M_real_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_352_pp0_iter8_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                sext_ln59_reg_446 <= sext_ln59_fu_347_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln53_reg_352_pp0_iter4_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_3_i_i_i_reg_431 <= grp_fu_237_p2;
                tmp_5_i_i_i_reg_436 <= grp_fu_241_p2;
                tmp_6_i_i_i_reg_441 <= grp_fu_245_p2;
                tmp_i_i_i_reg_426 <= grp_fu_233_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, icmp_ln53_fu_249_p2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((icmp_ln53_fu_249_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) and not(((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter16 = ap_const_logic_1)) or ((icmp_ln53_fu_249_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0)))) then
                    ap_NS_fsm <= ap_ST_fsm_state19;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state19 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    Llimit_fu_279_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(Ulimit_fu_273_p2));
    Ulimit_fu_273_p2 <= std_logic_vector(unsigned(butterfly_span_0_i_reg_176) + unsigned(shl_ln56_fu_267_p2));
    W_M_imag61_address0 <= sext_ln58_fu_285_p1(4 - 1 downto 0);

    W_M_imag61_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            W_M_imag61_ce0 <= ap_const_logic_1;
        else 
            W_M_imag61_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    W_M_real65_address0 <= sext_ln58_fu_285_p1(4 - 1 downto 0);

    W_M_real65_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            W_M_real65_ce0 <= ap_const_logic_1;
        else 
            W_M_real65_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state19 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state10_pp0_stage0_iter8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter9 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter10 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter11 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter12 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state15_pp0_stage0_iter13 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state16_pp0_stage0_iter14 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state17_pp0_stage0_iter15 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state18_pp0_stage0_iter16 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state7_pp0_stage0_iter5 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state8_pp0_stage0_iter6 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state9_pp0_stage0_iter7 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln53_fu_249_p2)
    begin
        if ((icmp_ln53_fu_249_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13, ap_enable_reg_pp0_iter14, ap_enable_reg_pp0_iter15, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_0) and (ap_enable_reg_pp0_iter15 = ap_const_logic_0) and (ap_enable_reg_pp0_iter14 = ap_const_logic_0) and (ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state19)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state19)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    butterfly_pass_10_fu_339_p3 <= 
        butterfly_pass_0_i_reg_187 when (tmp_fu_297_p3(0) = '1') else 
        butterfly_pass_9_fu_323_p3;
    butterfly_pass_9_fu_323_p3 <= 
        butterfly_pass_fu_317_p2 when (icmp_ln63_fu_311_p2(0) = '1') else 
        ap_const_lv32_0;
    butterfly_pass_fu_317_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(butterfly_pass_0_i_reg_187));
    butterfly_span_fu_305_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) + unsigned(butterfly_span_0_i_reg_176));
    data_IN_M_imag_address0 <= sext_ln58_5_fu_291_p1(5 - 1 downto 0);
    data_IN_M_imag_address1 <= sext_ln59_fu_347_p1(5 - 1 downto 0);

    data_IN_M_imag_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_IN_M_imag_ce0 <= ap_const_logic_1;
        else 
            data_IN_M_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_IN_M_imag_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_IN_M_imag_ce1 <= ap_const_logic_1;
        else 
            data_IN_M_imag_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    data_IN_M_real_address0 <= sext_ln58_5_fu_291_p1(5 - 1 downto 0);
    data_IN_M_real_address1 <= sext_ln59_fu_347_p1(5 - 1 downto 0);

    data_IN_M_real_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_IN_M_real_ce0 <= ap_const_logic_1;
        else 
            data_IN_M_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_IN_M_real_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter9)
    begin
        if (((ap_enable_reg_pp0_iter9 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_IN_M_real_ce1 <= ap_const_logic_1;
        else 
            data_IN_M_real_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    data_OUT1_M_imag_address0 <= sext_ln58_5_reg_376_pp0_iter15_reg(5 - 1 downto 0);
    data_OUT1_M_imag_address1 <= sext_ln59_reg_446_pp0_iter15_reg(5 - 1 downto 0);

    data_OUT1_M_imag_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_imag_ce0 <= ap_const_logic_1;
        else 
            data_OUT1_M_imag_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_OUT1_M_imag_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_imag_ce1 <= ap_const_logic_1;
        else 
            data_OUT1_M_imag_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    data_OUT1_M_imag_d0 <= complex_M_imag_writ_reg_491;
    data_OUT1_M_imag_d1 <= complex_M_imag_writ_5_reg_501;

    data_OUT1_M_imag_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln53_reg_352_pp0_iter15_reg, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln53_reg_352_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_imag_we0 <= ap_const_logic_1;
        else 
            data_OUT1_M_imag_we0 <= ap_const_logic_0;
        end if; 
    end process;


    data_OUT1_M_imag_we1_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln53_reg_352_pp0_iter15_reg, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln53_reg_352_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_imag_we1 <= ap_const_logic_1;
        else 
            data_OUT1_M_imag_we1 <= ap_const_logic_0;
        end if; 
    end process;

    data_OUT1_M_real_address0 <= sext_ln58_5_reg_376_pp0_iter15_reg(5 - 1 downto 0);
    data_OUT1_M_real_address1 <= sext_ln59_reg_446_pp0_iter15_reg(5 - 1 downto 0);

    data_OUT1_M_real_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_real_ce0 <= ap_const_logic_1;
        else 
            data_OUT1_M_real_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    data_OUT1_M_real_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_real_ce1 <= ap_const_logic_1;
        else 
            data_OUT1_M_real_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    data_OUT1_M_real_d0 <= complex_M_real_writ_reg_486;
    data_OUT1_M_real_d1 <= complex_M_real_writ_5_reg_496;

    data_OUT1_M_real_we0_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln53_reg_352_pp0_iter15_reg, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln53_reg_352_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_real_we0 <= ap_const_logic_1;
        else 
            data_OUT1_M_real_we0 <= ap_const_logic_0;
        end if; 
    end process;


    data_OUT1_M_real_we1_assign_proc : process(ap_block_pp0_stage0_11001, icmp_ln53_reg_352_pp0_iter15_reg, ap_enable_reg_pp0_iter16)
    begin
        if (((ap_enable_reg_pp0_iter16 = ap_const_logic_1) and (icmp_ln53_reg_352_pp0_iter15_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_OUT1_M_real_we1 <= ap_const_logic_1;
        else 
            data_OUT1_M_real_we1 <= ap_const_logic_0;
        end if; 
    end process;

    i_fu_255_p2 <= std_logic_vector(unsigned(i_0_i_reg_198) + unsigned(ap_const_lv5_1));
    icmp_ln53_fu_249_p2 <= "1" when (i_0_i_reg_198 = ap_const_lv5_10) else "0";
    icmp_ln63_fu_311_p2 <= "1" when (signed(butterfly_pass_0_i_reg_187) < signed(ap_const_lv32_F)) else "0";
    index_fu_261_p2 <= std_logic_vector(shift_left(unsigned(butterfly_span_0_i_reg_176),to_integer(unsigned('0' & ap_const_lv32_4(31-1 downto 0)))));
    select_ln61_fu_331_p3 <= 
        butterfly_span_fu_305_p2 when (tmp_fu_297_p3(0) = '1') else 
        ap_const_lv32_0;
        sext_ln58_5_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Llimit_fu_279_p2),64));

        sext_ln58_fu_285_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(index_fu_261_p2),64));

        sext_ln59_fu_347_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(Ulimit_reg_361_pp0_iter8_reg),64));

    shl_ln56_fu_267_p2 <= std_logic_vector(shift_left(unsigned(butterfly_pass_0_i_reg_187),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    tmp_fu_297_p3 <= butterfly_span_0_i_reg_176(31 downto 31);
end behav;
