// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _FFT_HH_
#define _FFT_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "FFT0.h"
#include "FFT_xin_M_real.h"
#include "FFT_rev_32.h"
#include "FFT_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 10,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct FFT : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    FFT(sc_module_name name);
    SC_HAS_PROCESS(FFT);

    ~FFT();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    FFT_xin_M_real* xin_M_real_U;
    FFT_xin_M_real* xin_M_imag_U;
    FFT_rev_32* rev_32_U;
    FFT_xin_M_real* data_OUT0_M_real_U;
    FFT_xin_M_real* data_OUT0_M_imag_U;
    FFT_xin_M_real* data_OUT1_M_real_U;
    FFT_xin_M_real* data_OUT1_M_imag_U;
    FFT_xin_M_real* data_OUT2_M_real_U;
    FFT_xin_M_real* data_OUT2_M_imag_U;
    FFT_xin_M_real* data_OUT3_M_real_U;
    FFT_xin_M_real* data_OUT3_M_imag_U;
    FFT_xin_M_real* data_OUT4_M_real_U;
    FFT_xin_M_real* data_OUT4_M_imag_U;
    FFT_xin_M_real* xout_M_real_U;
    FFT_xin_M_real* xout_M_imag_U;
    FFT_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* FFT_AXILiteS_s_axi_U;
    FFT0* grp_FFT0_fu_306;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<17> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<5> > data_IN_M_real_address0;
    sc_signal< sc_logic > data_IN_M_real_ce0;
    sc_signal< sc_lv<32> > data_IN_M_real_q0;
    sc_signal< sc_lv<5> > data_IN_M_imag_address0;
    sc_signal< sc_logic > data_IN_M_imag_ce0;
    sc_signal< sc_lv<32> > data_IN_M_imag_q0;
    sc_signal< sc_lv<5> > data_OUT_M_real_address0;
    sc_signal< sc_logic > data_OUT_M_real_ce0;
    sc_signal< sc_logic > data_OUT_M_real_we0;
    sc_signal< sc_lv<5> > data_OUT_M_imag_address0;
    sc_signal< sc_logic > data_OUT_M_imag_ce0;
    sc_signal< sc_logic > data_OUT_M_imag_we0;
    sc_signal< sc_lv<5> > xin_M_real_address0;
    sc_signal< sc_logic > xin_M_real_ce0;
    sc_signal< sc_logic > xin_M_real_we0;
    sc_signal< sc_lv<32> > xin_M_real_q0;
    sc_signal< sc_lv<5> > xin_M_imag_address0;
    sc_signal< sc_logic > xin_M_imag_ce0;
    sc_signal< sc_logic > xin_M_imag_we0;
    sc_signal< sc_lv<32> > xin_M_imag_q0;
    sc_signal< sc_lv<5> > rev_32_address0;
    sc_signal< sc_logic > rev_32_ce0;
    sc_signal< sc_lv<5> > rev_32_q0;
    sc_signal< sc_lv<5> > data_OUT0_M_real_address0;
    sc_signal< sc_logic > data_OUT0_M_real_ce0;
    sc_signal< sc_logic > data_OUT0_M_real_we0;
    sc_signal< sc_lv<32> > data_OUT0_M_real_q0;
    sc_signal< sc_lv<5> > data_OUT0_M_imag_address0;
    sc_signal< sc_logic > data_OUT0_M_imag_ce0;
    sc_signal< sc_logic > data_OUT0_M_imag_we0;
    sc_signal< sc_lv<32> > data_OUT0_M_imag_q0;
    sc_signal< sc_lv<5> > data_OUT1_M_real_address0;
    sc_signal< sc_logic > data_OUT1_M_real_ce0;
    sc_signal< sc_logic > data_OUT1_M_real_we0;
    sc_signal< sc_lv<32> > data_OUT1_M_real_q0;
    sc_signal< sc_lv<5> > data_OUT1_M_imag_address0;
    sc_signal< sc_logic > data_OUT1_M_imag_ce0;
    sc_signal< sc_logic > data_OUT1_M_imag_we0;
    sc_signal< sc_lv<32> > data_OUT1_M_imag_q0;
    sc_signal< sc_lv<5> > data_OUT2_M_real_address0;
    sc_signal< sc_logic > data_OUT2_M_real_ce0;
    sc_signal< sc_logic > data_OUT2_M_real_we0;
    sc_signal< sc_lv<32> > data_OUT2_M_real_q0;
    sc_signal< sc_lv<5> > data_OUT2_M_imag_address0;
    sc_signal< sc_logic > data_OUT2_M_imag_ce0;
    sc_signal< sc_logic > data_OUT2_M_imag_we0;
    sc_signal< sc_lv<32> > data_OUT2_M_imag_q0;
    sc_signal< sc_lv<5> > data_OUT3_M_real_address0;
    sc_signal< sc_logic > data_OUT3_M_real_ce0;
    sc_signal< sc_logic > data_OUT3_M_real_we0;
    sc_signal< sc_lv<32> > data_OUT3_M_real_q0;
    sc_signal< sc_lv<5> > data_OUT3_M_imag_address0;
    sc_signal< sc_logic > data_OUT3_M_imag_ce0;
    sc_signal< sc_logic > data_OUT3_M_imag_we0;
    sc_signal< sc_lv<32> > data_OUT3_M_imag_q0;
    sc_signal< sc_lv<5> > data_OUT4_M_real_address0;
    sc_signal< sc_logic > data_OUT4_M_real_ce0;
    sc_signal< sc_logic > data_OUT4_M_real_we0;
    sc_signal< sc_lv<32> > data_OUT4_M_real_q0;
    sc_signal< sc_lv<5> > data_OUT4_M_imag_address0;
    sc_signal< sc_logic > data_OUT4_M_imag_ce0;
    sc_signal< sc_logic > data_OUT4_M_imag_we0;
    sc_signal< sc_lv<32> > data_OUT4_M_imag_q0;
    sc_signal< sc_lv<5> > xout_M_real_address0;
    sc_signal< sc_logic > xout_M_real_ce0;
    sc_signal< sc_logic > xout_M_real_we0;
    sc_signal< sc_lv<32> > xout_M_real_q0;
    sc_signal< sc_lv<5> > xout_M_imag_address0;
    sc_signal< sc_logic > xout_M_imag_ce0;
    sc_signal< sc_logic > xout_M_imag_we0;
    sc_signal< sc_lv<32> > xout_M_imag_q0;
    sc_signal< sc_lv<6> > i_fu_368_p2;
    sc_signal< sc_lv<6> > i_reg_424;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<64> > zext_ln62_fu_374_p1;
    sc_signal< sc_lv<64> > zext_ln62_reg_429;
    sc_signal< sc_lv<1> > icmp_ln62_fu_362_p2;
    sc_signal< sc_lv<6> > i_1_fu_386_p2;
    sc_signal< sc_lv<6> > i_1_reg_448;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<64> > zext_ln18_fu_392_p1;
    sc_signal< sc_lv<64> > zext_ln18_reg_453;
    sc_signal< sc_lv<1> > icmp_ln17_fu_380_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<6> > i_2_fu_409_p2;
    sc_signal< sc_lv<6> > i_2_reg_477;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<64> > zext_ln72_fu_415_p1;
    sc_signal< sc_lv<64> > zext_ln72_reg_482;
    sc_signal< sc_lv<1> > icmp_ln72_fu_403_p2;
    sc_signal< sc_logic > grp_FFT0_fu_306_ap_start;
    sc_signal< sc_logic > grp_FFT0_fu_306_ap_done;
    sc_signal< sc_logic > grp_FFT0_fu_306_ap_idle;
    sc_signal< sc_logic > grp_FFT0_fu_306_ap_ready;
    sc_signal< sc_lv<6> > grp_FFT0_fu_306_FFT_stage;
    sc_signal< sc_lv<6> > grp_FFT0_fu_306_pass_check;
    sc_signal< sc_lv<4> > grp_FFT0_fu_306_index_shift;
    sc_signal< sc_lv<4> > grp_FFT0_fu_306_pass_shift;
    sc_signal< sc_lv<5> > grp_FFT0_fu_306_data_IN_M_real_address0;
    sc_signal< sc_logic > grp_FFT0_fu_306_data_IN_M_real_ce0;
    sc_signal< sc_lv<32> > grp_FFT0_fu_306_data_IN_M_real_q0;
    sc_signal< sc_lv<5> > grp_FFT0_fu_306_data_IN_M_imag_address0;
    sc_signal< sc_logic > grp_FFT0_fu_306_data_IN_M_imag_ce0;
    sc_signal< sc_lv<32> > grp_FFT0_fu_306_data_IN_M_imag_q0;
    sc_signal< sc_lv<5> > grp_FFT0_fu_306_data_OUT_M_real_address0;
    sc_signal< sc_logic > grp_FFT0_fu_306_data_OUT_M_real_ce0;
    sc_signal< sc_logic > grp_FFT0_fu_306_data_OUT_M_real_we0;
    sc_signal< sc_lv<32> > grp_FFT0_fu_306_data_OUT_M_real_d0;
    sc_signal< sc_lv<5> > grp_FFT0_fu_306_data_OUT_M_imag_address0;
    sc_signal< sc_logic > grp_FFT0_fu_306_data_OUT_M_imag_ce0;
    sc_signal< sc_logic > grp_FFT0_fu_306_data_OUT_M_imag_we0;
    sc_signal< sc_lv<32> > grp_FFT0_fu_306_data_OUT_M_imag_d0;
    sc_signal< sc_lv<6> > i_0_reg_273;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<6> > i_0_i_reg_284;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<6> > i1_0_reg_295;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > grp_FFT0_fu_306_ap_start_reg;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<64> > zext_ln19_fu_397_p1;
    sc_signal< sc_lv<17> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<17> ap_ST_fsm_state1;
    static const sc_lv<17> ap_ST_fsm_state2;
    static const sc_lv<17> ap_ST_fsm_state3;
    static const sc_lv<17> ap_ST_fsm_state4;
    static const sc_lv<17> ap_ST_fsm_state5;
    static const sc_lv<17> ap_ST_fsm_state6;
    static const sc_lv<17> ap_ST_fsm_state7;
    static const sc_lv<17> ap_ST_fsm_state8;
    static const sc_lv<17> ap_ST_fsm_state9;
    static const sc_lv<17> ap_ST_fsm_state10;
    static const sc_lv<17> ap_ST_fsm_state11;
    static const sc_lv<17> ap_ST_fsm_state12;
    static const sc_lv<17> ap_ST_fsm_state13;
    static const sc_lv<17> ap_ST_fsm_state14;
    static const sc_lv<17> ap_ST_fsm_state15;
    static const sc_lv<17> ap_ST_fsm_state16;
    static const sc_lv<17> ap_ST_fsm_state17;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<6> ap_const_lv6_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<6> ap_const_lv6_1;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<6> ap_const_lv6_2;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<6> ap_const_lv6_4;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<6> ap_const_lv6_8;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<6> ap_const_lv6_10;
    static const sc_lv<4> ap_const_lv4_4;
    static const sc_lv<4> ap_const_lv4_3;
    static const sc_lv<4> ap_const_lv4_2;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<4> ap_const_lv4_5;
    static const sc_lv<6> ap_const_lv6_20;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_data_IN_M_imag_address0();
    void thread_data_IN_M_imag_ce0();
    void thread_data_IN_M_real_address0();
    void thread_data_IN_M_real_ce0();
    void thread_data_OUT0_M_imag_address0();
    void thread_data_OUT0_M_imag_ce0();
    void thread_data_OUT0_M_imag_we0();
    void thread_data_OUT0_M_real_address0();
    void thread_data_OUT0_M_real_ce0();
    void thread_data_OUT0_M_real_we0();
    void thread_data_OUT1_M_imag_address0();
    void thread_data_OUT1_M_imag_ce0();
    void thread_data_OUT1_M_imag_we0();
    void thread_data_OUT1_M_real_address0();
    void thread_data_OUT1_M_real_ce0();
    void thread_data_OUT1_M_real_we0();
    void thread_data_OUT2_M_imag_address0();
    void thread_data_OUT2_M_imag_ce0();
    void thread_data_OUT2_M_imag_we0();
    void thread_data_OUT2_M_real_address0();
    void thread_data_OUT2_M_real_ce0();
    void thread_data_OUT2_M_real_we0();
    void thread_data_OUT3_M_imag_address0();
    void thread_data_OUT3_M_imag_ce0();
    void thread_data_OUT3_M_imag_we0();
    void thread_data_OUT3_M_real_address0();
    void thread_data_OUT3_M_real_ce0();
    void thread_data_OUT3_M_real_we0();
    void thread_data_OUT4_M_imag_address0();
    void thread_data_OUT4_M_imag_ce0();
    void thread_data_OUT4_M_imag_we0();
    void thread_data_OUT4_M_real_address0();
    void thread_data_OUT4_M_real_ce0();
    void thread_data_OUT4_M_real_we0();
    void thread_data_OUT_M_imag_address0();
    void thread_data_OUT_M_imag_ce0();
    void thread_data_OUT_M_imag_we0();
    void thread_data_OUT_M_real_address0();
    void thread_data_OUT_M_real_ce0();
    void thread_data_OUT_M_real_we0();
    void thread_grp_FFT0_fu_306_FFT_stage();
    void thread_grp_FFT0_fu_306_ap_start();
    void thread_grp_FFT0_fu_306_data_IN_M_imag_q0();
    void thread_grp_FFT0_fu_306_data_IN_M_real_q0();
    void thread_grp_FFT0_fu_306_index_shift();
    void thread_grp_FFT0_fu_306_pass_check();
    void thread_grp_FFT0_fu_306_pass_shift();
    void thread_i_1_fu_386_p2();
    void thread_i_2_fu_409_p2();
    void thread_i_fu_368_p2();
    void thread_icmp_ln17_fu_380_p2();
    void thread_icmp_ln62_fu_362_p2();
    void thread_icmp_ln72_fu_403_p2();
    void thread_rev_32_address0();
    void thread_rev_32_ce0();
    void thread_xin_M_imag_address0();
    void thread_xin_M_imag_ce0();
    void thread_xin_M_imag_we0();
    void thread_xin_M_real_address0();
    void thread_xin_M_real_ce0();
    void thread_xin_M_real_we0();
    void thread_xout_M_imag_address0();
    void thread_xout_M_imag_ce0();
    void thread_xout_M_imag_we0();
    void thread_xout_M_real_address0();
    void thread_xout_M_real_ce0();
    void thread_xout_M_real_we0();
    void thread_zext_ln18_fu_392_p1();
    void thread_zext_ln19_fu_397_p1();
    void thread_zext_ln62_fu_374_p1();
    void thread_zext_ln72_fu_415_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
